services:
  - type: web
    name: Diabetes_Detection_System
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
